name = "JensenLab"
uuid = "4808f7ef-8369-42aa-aeb9-deb076640aa4"
repo = "https://github.com/jensenlab/JensenLabRegistry"
description = "The Jensen Lab Julia Registry"

[packages]
52f550af-10d2-4094-8a84-3f014d56cfcb = { name = "PlateArrays", path = "P/PlateArrays" }
