name = "JensenLab"
uuid = "4808f7ef-8369-42aa-aeb9-deb076640aa4"
repo = "https://github.com/jensenlab/JensenLabRegistry"
description = "The Jensen Lab Julia Registry"

[packages]
40aca73e-78db-4064-9398-4788728e7bb7 = { name = "JLIMS", path = "J/JLIMS" }
52f550af-10d2-4094-8a84-3f014d56cfcb = { name = "PlateArrays", path = "P/PlateArrays" }
82aece00-2e0a-4aa7-b3de-eea0746b1d2e = { name = "Pourfecto", path = "P/Pourfecto" }
